apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-tpl
spec:
  entrypoint: create-team
  arguments:
    parameters:
      - name: teamName
        description: "The name of the team"
  templates:
    - name: fake-template
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command: [echo, "{{inputs.parameters.message}}"]
    - name: fail
      retryStrategy:
        limit: 3
        retryPolicy: "Always"
      script:
        image: alpine:3.7
        command: [sh]
        source: |
          echo 'break pipeline'
          exit 1
    - name: create-team
      dag:
        tasks:
        - name: github-team
          template: fake-template
          arguments:
            parameters:
              - name: message
                value: "Create GitHub {{workflow.parameters.teamName}}"
        - name: keycloak-team
          template: fake-template
          arguments:
            parameters:
              - name: message
                value: Create keycloak team
        - name: artifactory-team
          template: fake-template
          arguments:
            parameters:
              - name: message
                value: Create artifactory team
        - name: sonar-team
          template: fake-template
          arguments:
            parameters:
              - name: message
                value: Create artifactory team
        - name: notify-success
          template: fake-template
          dependencies:
            - github-team
            - keycloak-team
            - artifactory-team
            - sonar-team
            - fail
          arguments:
            parameters:
              - name: message
                value: The team has been created
        - name: fail
          template: fail

---

apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: create-team
spec:
  event:
    # metadata header name must be lowercase to match in selector
    selector: payload.message != "" && discriminator == "create-team"
  submit:
    workflowTemplateRef:
      name: workflow-tpl
    arguments:
      parameters:
      - name: teamName
        valueFrom:
          event: payload.message